# Base image with Ubuntu 22.04
FROM ubuntu:22.04

# Install system packages
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-dev \
    libpq-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy dependencies and install them
COPY requirements.txt /app/
RUN pip3 install --no-cache-dir -r requirements.txt

# Copy app code
COPY . /app

# Set environment variables 
# python app tells python where to look for modules
# flask_App tells flask which file to run
#flask_run_host ensures flasks listens to all network interfaces so its avaialble outside the container
ENV PYTHONPATH=/app 
ENV FLASK_APP=app
ENV FLASK_RUN_HOST=0.0.0.0

# Expose Flask port
EXPOSE 5000

# Run the Flask app, specifies the default command to run when container starts
CMD ["flask", "run", "--host=0.0.0.0"]
